### ISSUE TITLE
参与中文翻译

### ISSUE THREAD

**Issue by JohnieXu** [denocn/deno_docs#1]
想参与该项目的中文翻译，请问可行吗

**Comment by hsiaosiyuan0** [comment]
我觉得可行

**Comment by justjavac** [comment]
我觉得可行

**Comment by justjavac** [comment]
@Nugine 已经翻译完了 🎉 https://github.com/Nugine/deno-manual-cn

**Comment by hylerrix** [comment]
> @Nugine 已经翻译完了 🎉 https://github.com/Nugine/deno-manual-cn

@justjavac 既然已经翻译完了，这个仓库怎么处理？还需要翻译吗？
